stages:
  - test
  - tweet
  - deploy

test_job:
  stage: test
  script:
    - ci/mailtrain_build

tweet_succeed_job:
  variables:
    PASSED: "true"
  stage: tweet
  only:
    - tags
    - triggers
    - master
  script:
    - ci/mailtrain_tweet

tweet_failed_job:
  variables:
    PASSED: "false"
  stage: tweet
  only:
    - tags
    - triggers
    - master
  script:
    - ci/mailtrain_tweet
  when: on_failure

deploy_job:
  stage: deploy
  only:
    - tags
    - triggers
    - master
  script:
    - ci/mailtrain_deploy
