version : '2'

services:
  mailtrain:
    image: evild/alpine-mailtrain:1.13.0
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=mailtrain
      - MYSQL_DATABASE=mailtrain
      - MYSQL_USER=mailtrain
      - MYSQL_PASSWORD=mailtrain
