version : '2'

services:
  mailtrain:
    image: otlet/docker-alpine-mailtrain:latest
    networks:
      - front
      - back
    ports:
      - 3000:3000
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mailtrain
      - MYSQL_DATABASE=mailtrain
      - MYSQL_USER=mailtrain
      - MYSQL_PASSWORD=mailtrain
    networks:
      - back
networks:
  front:
  back:
