#!/bin/sh

set -e


docker build -t evild/alpine-mailtrain:latest .
docker inspect evild/alpine-mailtrain:latest

#git checkout master
#git push --mirror https://$GITHUB_TOKEN@github.com/Evild67/docker-alpine-nginx.git

docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
docker push evild/alpine-mailtrain:latest
