#!/bin/sh
set -e

default_text="Gitlab Job $CI_BUILD_ID :"

tweet_text="$default_text #Docker mailtrain $CI_BUILD_REF_NAME build"

if [ $PASSED = true ]; then
  tweet_text="$tweet_text succeed https://mercu.re/25xVQDM"
else
  tweet_text="$tweet_text failed https://mercu.re/25xVQDM"
fi



docker run --rm  -e TWITTER_ACCESS_TOKEN_SECRET=$TWITTER_ACCESS_TOKEN_SECRET -e TWITTER_ACCESS_TOKEN_KEY=$TWITTER_ACCESS_TOKEN_KEY -e TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET -e TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY evild/twitter_build_bot:latest "$tweet_text"
