#!/bin/sh

set -e


docker build -t evild/alpine-mailtrain:latest .
docker inspect evild/alpine-mailtrain:latest


docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
docker push evild/alpine-mailtrain:latest
