#!/bin/sh

set -e


docker build -t otlet/alpine-mailtrain:latest .
docker inspect otlet/alpine-mailtrain:latest


docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
docker push otlet/alpine-mailtrain:latest
